build:
    name: 'CFX Rig'
    name_chs: '解算预设'

    tool_tip:
        |-
        To be supplemented.

    tool_tip_chs:
        |-
        待补充。

    buttons:
        apply_and_close:
            name: 'Apply and Close'
            name_chs: '应用并关闭'

        apply:
            name: 'Apply'
            name_chs: '应用'

        close:
            name: 'Close'
            name_chs: '关闭'

    options:
        name: 'Options'
        name_chs: '选项'

        parameters:
            upstream:
                widget: group
                name: 'Upstream'
                name_chs: '上游'

            upstream/scene:
                widget: file
                open_or_save: open
                name: 'Scene'
                name_chs: '文件'

            upstream/scene_modify_time:
                widget: string
                name: 'Scene Modify Time'
                name_chs: '文件修改时间'
                tool_tip: 'To be supplemented.'
                tool_tip_chs: '显示上游文件修改时间。'
                lock: True

            upstream/preview:
                widget: file
                open_or_save: open
                name: 'Preview'
                name_chs: '预览'
                lock: True

            upstream/play_preview:
                widget: button
                name: 'Play Preview'
                name_chs: '播放预览'

            task_unit:
                widget: enumerate
                name: 'Task Unit'
                name_chs: '任务单元'
                options: ['main', 'test']
                default: 'main'

            use_current_scene:
                widget: boolean
                name: 'Use Current Scene'
                name_chs: '使用当前文件'
                value: False