option:
    type: rsv-task-method
    #
    systems:
        - '*-*'
    #
    gui:
        group_name: ''
        #
        name: ''
        icon_name: ''
#
hook_option:
    engine: maya
    #
    script:
        # scene file-path
        batch_file: ''
        #
        file: ''
        #
        open_file: True
        save_file: False
    #
    deadline:
        #
        group: all
        #
        pool: emergency
    #
    rez:
        extend_packages: []
