roots:
    disorder:
        windows: 'X:'

    source:
        windows: 'Z:/projects'

    release:
        windows: 'X:'

    temporary:
        windows: 'Z:/projects'

spaces:
    disorder : 'disorder'
    source: 'source'
    release: 'release'
    temporary: 'temporary'

patterns:
    # project
    project:
        release:
            dir: '{root_release}/{project}/QSM/{space}'

    # asset
    asset:
        task-version-name: '{asset}.{step}.{task}.v{version}'
        task_unit-version-name: '{asset}.{step}.{task}.{task_unit}.v{version}'

        disorder:
            rig_scene-maya-file: '{root_disorder}/{project}/Assets/{role}/{asset}/Rig/Final/scenes/{asset}_Skin.ma'

        source:
            dir: '{root_source}/{project}/{space}/assets/{role}/{asset}'
            # task
            task-dir: '<.dir>/user.{artist}/{step}.{task}'
            task_unit-dir: '<.task-dir>/{task_unit}'
            # files
            maya-scene_src-file: '<.task_unit-dir>/maya/scenes/<..task_unit-version-name>.ma'
            maya-thumbnail-file: '<.task_unit-dir>/maya/.thumbnails/<..task_unit-version-name>.jpg'

        release:
            dir: '{root_release}/{project}/QSM/{space}/assets/{role}/{asset}'
            # task
            task-dir: '<.dir>/{step}.{task}'
            # task version
            task_version-dir: '<.task-dir>/<..task-version-name>'
            # files
            maya-scene_src-file: '<.task_version-dir>/source/{asset}.ma'
            preview-file: '<.task_version-dir>/preview/<..task-version-name>.mov'

            maya-scene-file: '<.task_version-dir>/maya/{asset}.ma'
            connect_map-json-file: '<.task_version-dir>/json/{asset}.connect_map.json'

        temporary:
            dir: '{root_temporary}/{project}/source/assets/{role}/{asset}'
            # task
            task-dir: '<.dir>/{step}.{task}'

    shot:
        task-version-name: '{shot}.{step}.{task}.v{version}'
        task_unit-version-name: '{shot}.{step}.{task}.{task_unit}.v{version}'

        disorder:
            animation_scene-file: '{root_disorder}/{project}/{episode}/{sequence}/动画/通过文件/{shot}.ma'

        source:
            dir: '{root_source}/{project}/{space}/shots/{sequence}/{shot}'
            # task
            task-dir: '<.dir>/user.{artist}/{step}.{task}'
            task_unit-dir: '<.task-dir>/{task_unit}'
            # files
            maya-scene_src-file: '<.task_unit-dir>/maya/scenes/<..task_unit-version-name>.ma'
            maya-thumbnail-file: '<.task_unit-dir>/maya/.thumbnails/<..task_unit-version-name>.jpg'
            # directories
            maya-cache-dir: '<.task_unit-dir>/maya/caches'
            maya-cloth_cache-dir: '<.task_unit-dir>/maya/cloth_caches'

        release:
            dir: '{root_release}/{project}/{space}/shots/{sequence}/{shot}'
