build:
    messages:
        no_characters:
            message_chs: '选择一个或者多个角色（可以是任意部件）。'
            message: 'Select one or more character (any part).'

    basic:
        name: 'basic'
        name_chs: '基础'

        tool_tip:
            |-
            To be supplemented.

        tool_tip_chs:
            |-
            待补充。

        options:
            name: 'Options'
            name_chs: '选项'

            parameters:
                template:
                    widget: group
                    name: 'Template'
                    name_chs: '模版'

                template/create_groups:
                    widget: button
                    name: 'Create Group'
                    name_chs: '创建分组'
                    icon: 'tool/create'
                    tool_tip:
                        |-
                        To be supplemented.
                    tool_tip_chs:
                        |-
                        点击创建分组：
                            默认在任务创建的时候会自动创建分组，如果没通过任务创建工具可使用这个功能创建分组。

                cfx_rig:
                    widget: group
                    name: 'CFX Rig'
                    name_chs: '解算预设'
                    tool_tip:
                        |-
                        To be supplemented.
                    tool_tip_chs:
                        |-
                        解算预设相关的功能。

                cfx_rig/load_or_update_force:
                    widget: boolean
                    name: 'Load / Update Force'
                    name_chs: '强制加载 / 更新'

                    tool_tip:
                        |-
                        To be supplemented.
                    tool_tip_chs:
                        |-
                        当这个选项被勾起的时候，会强制更新解算预设到默认状态，并移除所有的修改。

                cfx_rig/load_or_update:
                    widget: button
                    name: 'Load / Update CFX Rig'
                    name_chs: '加载 / 更新解算预设'
                    icon: 'file/add-file'
                    menu_enable: True
                    tool_tip:
                        |-
                        To be supplemented.
                    tool_tip_chs:
                        |-
                        点击加载解算预设，需要选中绑定，可以是任意部件:
                            目前更新功能可能会出现BUG。

                cfx_rig/enable:
                    widget: button
                    name: 'Enable CFX Rig'
                    name_chs: '启用解算预设'
                    icon: 'tool/enable'
                    join_to_next: True
                    tool_tip:
                        |-
                        To be supplemented.
                    tool_tip_chs:
                        |-
                        点击启用解算预设：
                            当解算预设被禁用的时候可以使用这个按钮。

                cfx_rig/disable:
                    widget: button
                    name: 'Disable CFX Rig'
                    name_chs: '禁用解算预设'
                    icon: 'tool/disable'
                    tool_tip:
                        |-
                        To be supplemented.
                    tool_tip_chs:
                        |-
                        点击禁用解算预设：
                            只有解算预设被加载了才能使用这个按钮禁用。

                cfx_rig/load_rig_preset:
                    widget: button
                    name: 'Load Rig Preset (Cloth)'
                    name_chs: '加载预设模版（布料）'
                    use_name_icon: True
                    tool_tip:
                        |-
                        To be supplemented.
                    tool_tip_chs:
                        |-
                        点击加载预设模版：
                            只有资产解算预设阶段做过“预设模版”才能正确加载。

                ani_cache:
                    widget: group
                    name: 'Animation Cache'
                    name_chs: '动画缓存'
                    tool_tip:
                        |-
                        To be supplemented.
                    tool_tip_chs:
                        |-
                        动画缓存相关的功能。

                ani_cache/load_or_update:
                    widget: button
                    name: 'Load / Update Animation Cache'
                    name_chs: '加载 / 更新动画缓存'
                    icon: 'file/add-file'
                    menu_enable: True
                    tool_tip:
                        |-
                        To be supplemented.
                    tool_tip_chs:
                        |-
                        点击加载/ 更新动画缓存，需要选中绑定，可以是任意部件：
                            目前更新功能可能会出现BUG。

                simulation:
                    widget: group
                    name: 'Simulation'
                    name_chs: '解算'
                    tool_tip:
                        |-
                        To be supplemented.
                    tool_tip_chs:
                        |-
                        解算相关的功能。

                simulation/solver:
                    widget: group
                    name: 'Solver'
                    name_chs: '解算器'
                    tool_tip:
                        |-
                        To be supplemented.
                    tool_tip_chs:
                        |-
                        解算器相关的功能。

                simulation/solver/enable:
                    widget: button
                    name: 'Enable Solver (selected)'
                    name_chs: '启用解算器（选中）'
                    icon: 'tool/enable'
                    join_to_next: True
                    tool_tip:
                        |-
                        To be supplemented.
                    tool_tip_chs:
                        |-
                        启用解算器：
                            选中一个或多个角色，然后点击按钮。

                simulation/solver/disable:
                    widget: button
                    name: 'Disable Solver (selected)'
                    name_chs: '禁用解算器（选中）'
                    icon: 'tool/disable'
                    tool_tip:
                        |-
                        To be supplemented.
                    tool_tip_chs:
                        |-
                        禁用解算器：
                            当解算的角色过多的时候，可以使用这个功能停止某些角色的运算;
                            选中一个或多个角色，然后点击按钮。

                simulation/select_all_asset:
                    widget: button
                    name: 'Select All Asset'
                    name_chs: '选择所有资产'
                    icon: 'tool/maya/select'
                    tool_tip:
                        |-
                        To be supplemented.
                    tool_tip_chs:
                        |-
                        点击选中所有的绑定。

    export:
        name: 'Export'
        name_chs: '导出'

        tool_tip: 'To be supplemented.'
        tool_tip_chs: '待补充。'

        options:
            name: 'Options'
            name_chs: '选项'

            parameters:
                setting:
                    widget: group
                    name: 'Setting'
                    name_chs: '设置'
                    collapse: True

                setting/fps:
                    widget: capsule_string
                    name: 'FPS'
                    name_chs: '帧率'
                    options: ['24_fps', '30_fps']
                    default: '24_fps'
                    tool_tip: 'show scene FPS'
                    tool_tip_chs: '显示当前场景的帧率。'
                    lock: True

                setting/frame_scheme:
                    widget: capsule_string
                    name: 'Frame Scheme'
                    name_chs: '帧方案'
                    options: ['time_slider', 'frame_range']
                    option_names_chs: ['时间轴', '帧范围']
                    default: 'time_slider'
                    enable: True
                    tool_tip: 'choose a frame scheme'
                    tool_tip_chs:
                        |-
                        设置一个帧方案:
                            时间轴：自动读取帧范围；
                            帧范围：在帧范围中输入。

                setting/frame_range:
                    widget: integer2
                    name: 'Frame Range'
                    name_chs: '帧范围'
                    value: [0, 24]
                    lock: True
                    visible_condition: {
                        operator: 'is', port: 'setting/frame_scheme', value: 'frame_range'
                    }
                    tool_tip:
                        |-
                        To be supplemented.
                    tool_tip_chs:
                        |-
                        当帧方案为帧范围的时候这个功能才可用。

                setting/frame_offset:
                    widget: integer
                    name: 'Frame Offset'
                    name_chs: '帧偏移'
                    value: 0
                    visible: False
                    tool_tip:
                        |-
                        To be supplemented.
                    tool_tip_chs:
                        |-
                        设置帧偏移，这个功能暂时不可用。

                setting/frame_step:
                    widget: integer
                    name: 'Frame Step'
                    name_chs: '帧步长'
                    value: 1
                    tool_tip:
                        |-
                        To be supplemented.
                    tool_tip_chs:
                        |-
                        设置帧步长，这行功能暂时不可用。

                animation:
                    widget: group
                    name: 'Animation'
                    name_chs: '动画'

                animation/start_frame:
                    widget: integer
                    name: 'Animation Start Frame'
                    name_chs: '动画起始帧'
                    value: 0
                    tool_tip:
                        |-
                        To be supplemented.
                    tool_tip_chs:
                        |-
                        设置动画起始帧。

                animation/apply_start_frame:
                    widget: button
                    name: 'Apply Animation Start Frame'
                    name_chs: '应用动画起始帧'
                    icon: 'tool/time'
                    tool_tip:
                        |-
                        To be supplemented.
                    tool_tip_chs:
                        |-
                        点击应用上面设置的初始帧。

                simulation:
                    widget: group
                    name: 'Solver'
                    name_chs: '解算'

                simulation/start_frame:
                    widget: integer
                    name: 'Solver Start Frame'
                    name_chs: '解算起始帧'
                    value: 0
                    tool_tip:
                        |-
                        To be supplemented.
                    tool_tip_chs:
                        |-
                        设置动画起始帧。

                simulation/apply_start_frame:
                    widget: button
                    name: 'Apply Solver Start Frame'
                    name_chs: '应用解算起始帧'
                    icon: 'tool/time'
                    tool_tip:
                        |-
                        To be supplemented.
                    tool_tip_chs:
                        |-
                        点击应用上面设置的初始帧。

                cache_directory:
                    widget: group
                    name: 'Cache Directory'
                    name_chs: '缓存目录'
                    tool_tip:
                        |-
                        To be supplemented.
                    tool_tip_chs:
                        |-
                        缓存输出相关。

                cache_directory/version_scheme:
                    widget: capsule_string
                    name: 'Version Scheme'
                    name_chs: '版本方案'
                    options: ['no_version', 'new_version', 'specified_version']
                    option_names_chs: ['无版本', '新版本', '指定版本']
                    default: 'new_version'
                    enable: True
                    tool_tip:
                        |-
                        To be supplemented.
                    tool_tip_chs:
                        |-
                        设置输出缓存的方案：
                            默认为新版本，推荐使用这个方案；
                            当你需要覆盖某个版本的缓存可以使用指定版本。

                cache_directory/specified_version:
                    widget: integer
                    name: 'Specified Version'
                    name_chs: '指定版本'
                    value: 0
                    visible_condition: {
                        operator: 'is', port: 'cache_directory/version_scheme', value: 'specified_version'
                    }
                    tool_tip:
                        |-
                        To be supplemented.
                    tool_tip_chs:
                        |-
                        输入指定的版本数字。

                cache_directory/directory:
                    widget: directory
                    open_or_save: save
                    name: 'Export Directory'
                    name_chs: '导出目录'
                    value: ''
                    history_key: 'tool-panels.lazy-cfx-tool.cache_directory-export-version-directory-open'
                    tool_tip:
                        |-
                        To be supplemented.
                    tool_tip_chs:
                        |-
                        缓存目录，默认是自动设置的，也可手动设置，但是不推荐。

                cache_directory/version_directory:
                    widget: directory
                    open_or_save: save
                    name: 'Export Version Directory'
                    name_chs: '导出版本目录'
                    value: ''
                    lock: True
                    tool_tip:
                        |-
                        To be supplemented.
                    tool_tip_chs:
                        |-
                        最终输出的版本文件夹，不可手动设置。

                preview_export:
                    widget: group
                    name: 'Preview Export'
                    name_chs: '预览导出'
                    tool_tip:
                        |-
                        To be supplemented.
                    tool_tip_chs:
                        |-
                        预览拍屏相关。

                preview_export/playblast:
                    widget: button
                    name: 'Playblast'
                    name_chs: '拍屏'
                    icon: 'tool/maya/playblast'
                    menu_enable: True
                    tool_tip:
                        |-
                        To be supplemented.
                    tool_tip_chs:
                        |-
                        点击拍屏，右键点击/点击右边三个点可以查看更多功能：
                            子进程：
                                使用子进程进行拍屏；
                            后台：
                                使用后台进程进行拍屏，需要打开“懒人后台任务管理”；
                            农场：
                                使用农场进行拍屏。

                cache_export:
                    widget: group
                    name: 'Cache Export'
                    name_chs: '缓存导出'
                    tool_tip:
                        |-
                        To be supplemented.
                    tool_tip_chs:
                        |-
                        缓存导出相关。

                cache_export/scheme:
                    widget: capsule_string
                    name: 'Export Scheme'
                    name_chs: '导出方案'
                    options: ['all', 'selected']
                    option_names: ['All', 'Selected']
                    option_names_chs: ['所有', '选中的']
                    default: 'all'
                    tool_tip:
                        |-
                        To be supplemented.
                    tool_tip_chs:
                        |-
                        默认为导出所有，如果需要导出选择，请选中需要导出的绑定，可以是任意部件。

                cache_export/export_cloth_cache:
                    widget: button
                    name: 'Export Cache'
                    name_chs: '导出CFX布料'
                    icon: 'upload'
                    menu_enable: True
                    tool_tip:
                        |-
                        To be supplemented.
                    tool_tip_chs:
                        |-
                        点击导出布料缓存，右键点击/点击右边三个点可以查看更多功能：
                            子进程：
                                使用子进程进行缓存导出；
                            后台：
                                使用后台进程进行缓存导出，需要打开“懒人后台任务管理”；
                            农场：
                                使用农场进行缓存导出。