entities:
    resolve_patterns:
        # entity_type: pattern
        Project: '{root}/{project}/Assets'
        Role: '{root}/{project}/Assets/{role}'
        Asset: '{root}/{project}/Assets/{role}/{asset}'
        Episode: '{root}/{project}/{episode}'
        # do not add "{seq_IGN}"
        Sequence:
            - '{root}/{project}/{episode}/{sequence}/分镜'
            - '{root}/{project}/{episode}/{sequence}/动画'
        # sequence variant has chinese word, so add "{seq_IGN}" for match result.
        Shot:
            - '{root}/{project}/{episode}/{sequence}{seq_IGN}/分镜/通过文件/{shot}.ma'
            - '{root}/{project}/{episode}/{sequence}{seq_IGN}/动画/通过文件/{shot}.ma'
        #
        ProjectTask: ''
        AssetTask: '{root}/{project}/Assets/{role}/{asset}/{task}/Final'
        SequenceTask: ''
        ShotTask: '{root}/{project}/{episode}/{sequence}{seq_IGN}/{task}/通过文件/{shot}.ma'

    path_patterns:
        User: '/{user}'
        Root: '/{root}'
        Project: '/{project}'
        ResourceType: '/{project}/{resource_type}'
        Role: '/{project}/{role}'
        Asset: '/{project}/{role}/{asset}'
        Episode: '/{project}/{episode}'
        Sequence: '/{project}/{sequence}'
        Shot: '/{project}/{sequence}/{shot}'
        Step: '/{project}/{resource_type}/{step}'
        Task: '{entity_path}/{task}'

    variant_keys:
        Department: 'department'
        User: 'user'
        #
        Root: 'root'
        #
        Project: 'project'
        #
        ResourceType: 'resource_type'
        #
        Role: 'role'
        Asset: 'asset'
        Episode: 'episode'
        Sequence: 'sequence'
        Shot: 'shot'
        #
        Step: 'step'
        Task: 'task'
        #
        Version: 'version'

    variant_key_regexes:
        project: '[a-zA-Z]*'
        role: '[a-zA-Z]*'
        asset: '[a-zA-Z]*'
        #
        episode: '[a-zA-Z]*[0-9]*'
        sequence: '[a-zA-Z]*'
        shot: '[a-zA-Z]*[0-9]'

    variant_cleanup_keys:
        - sequence

steps:
    concept: 'Design'
    model: 'Maya'
    rig: 'Rig'
    surface: 'UE'

    layout: 'Layout'
    animation: '动画'

tasks:
    concept: 'Design'
    model: 'Maya'
    rig: 'Rig'
    surface: 'UE'

    layout: 'Layout'
    animation: '动画'
    
workspace:
    tasks:
        project: {}
        asset:
            concept:
                - concept
            model:
                - model
            rig:
                - rig
            surface:
                - surface
        episode: {}
        sequence: {}
        shot:
            layout:
                - layout
            animation:
                - animation

patterns:
    MayaRigFile: '{root}/{project}/Assets/{role}/{asset}/Rig/Final/scenes/{asset}_Skin.ma'
    MayaModelFIle: '{root}/{project}/Assets/{role}/{asset}/Maya/Final/{asset}.ma'

    MayaLayoutFile: '{root}/{project}/{episode}/{sequence}{seq_IGN}/分镜/通过文件/{shot}.ma'
    MayaAnimationFile: '{root}/{project}/{episode}/{sequence}{seq_IGN}/动画/通过文件/{shot}.ma'
